feat(oauth2) : 카카오, 구글 소셜 로그인 구현
Programmers-Coach-Coach/Coach-Coach-server pull request #323
Opened 2024-10-08 12:04 UTC by hanbirang

# Pull requests
### 작업한 내용
- Google 및 Kakao OAuth2 인증 로직 구현
- OAuth2 인증 성공 시 JWT 토큰 생성 및 쿠키에 저장하는 로직 추가
- 사용자 정보 저장 및 업데이트 로직 구현 (OAuth2 사용자 정보 기반)
- GoogleResponse, KakaoResponse 클래스 추가하여 각 OAuth 공급자에서 받은 정보를 표준화
- CustomOAuth2UserService 및 CustomOAuth2Handler 클래스 구현을 통해 OAuth2 인증 후 사용자 정보를 처리하고 JWT를 발행하는 기능 추가

### PR Point
- `application.properties` 내용 공유해드리겠습니다 업데이트해주세요!
- 작동 방식은 아래와 같습니다
![image](https://github.com/user-attachments/assets/1fe0160d-e5f2-43ee-91ca-b732404bced5)
- 프론트단에서 백엔드의 OAuth2 로그인 경로로 하이퍼링킹을 진행 후 백엔드단에서 로그인 페이지 요청 → 코드 발급 → Access 토큰 → 유저 정보 획득 → JWT 발급

```tsx
// src/App.tsx
import React, { useEffect, useState } from "react";

const App: React.FC = () => {
  const [authStatus, setAuthStatus] = useState<string>("");

  useEffect(() => {
    // 쿠키를 이용해서 인증 여부를 체크하는 함수
    const checkAuthentication = async () => {
      const response = await fetch("/auth/status", {
        credentials: "include", // 쿠키 전송 허용
      });

      if (response.ok) {
        const data = await response.json();
        setAuthStatus(`Authenticated as: ${data.username}`);
      } else {
        setAuthStatus("Not authenticated");
      }
    };

    checkAuthentication();
  }, []);

  const handleGoogleLogin = () => {
    window.location.href = "http://localhost:8080/oauth2/authorization/google";
  };

  const handleKakaoLogin = () => {
    window.location.href = "http://localhost:8080/oauth2/authorization/kakao";
  };

  return (
    <div>
      <h1>OAuth2 Login Test</h1>
      <p>{authStatus}</p>
      <button onClick={handleGoogleLogin}>Login with Google</button>
      <button onClick={handleKakaoLogin}>Login with Kakao</button>
    </div>
  );
};

export default App;
```
아래와 같이 작성한 뒤 테스트 해보았습니다. 

### 📸 스크린샷

|사진|설명|
|---|---|
|![image](https://github.com/user-attachments/assets/7d238669-ee68-4795-80c0-91d3da853b00)| 홈 화면 |
|![image](https://github.com/user-attachments/assets/1ac5635d-f738-49f1-80f3-21280e4ef0a6)| 카카오 클릭 시 카카오 로그인으로 로딩 |

마찬가지로 구글일 경우에도 구글 로그인창으로 이동합니다.

closed #321

2024-10-10 07:21 UTC, ckwogus37 approved these changes
확인했습니다!

2024-10-10 07:58 UTC, jeeehdev approved these changes
확인했습니다!!

2024-10-12 05:21 UTC, ksy90101 requested changes
뭔가 구조가...
하나의 이메일은 

일반회원가입 - 구글 - 카카오

이 셋중에 하나만 가능한거 같은데 맞나요?

2024-10-12 05:21 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/auth/oauth/CustomOAuth2Handler.java
> +		tokenService.createRefreshToken(user, tokenDto.refreshToken(), tokenDto);
해당 부분에 대한 중복로직 제거를 해보면 어떨까요?
메서드를 추출하는 방법도 있을테고.
배열을 만들어서 for문을 도는것도 있겠네요.
혹은 전략패턴같은걸 쓸수도 있겠죠.

2024-10-12 05:21 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/auth/oauth/CustomOAuth2UserService.java
> +	public OAuth2User loadUser(OAuth2UserRequest userRequest) throws OAuth2AuthenticationException {
메서드를 분리하여 의미를 나타내는것부터 해보면 어덜까요?

각 라인이 어떤 일을 하는지를 말이죠.

그러면 그때부터 리팩토링과 확장할수 있는 영역들이 보이기 시작한답니다.

2024-10-12 05:21 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/auth/oauth/dto/CustomOAuth2User.java
> +	private final User user;
user를 가지고 있는 이유가 무엇인가요?

2024-10-12 05:21 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +	private Boolean isSocial;
isSocial도 좋지만.
궁금한게

한 사용자는 하나의 social로그인밖게 못하나요?

즉. 현재 구글과 카카오 둘다 연동할순 없나요?

2024-10-12 05:21 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +	private String username;
본명을 저장하고 싶은건가요?
본명을 주나요?
이게 왜 있는건가요?

2024-10-13 03:58 UTC, hanbirang commented
> 뭔가 구조가... 하나의 이메일은
> 
> 일반회원가입 - 구글 - 카카오
> 
> 이 셋중에 하나만 가능한거 같은데 맞나요?

네 맞습니당

2024-10-13 05:00 UTC, ksy90101 commented
동일한 이메일로 가입하려고 하면 어떻게 되나요?

2024-10-13 05:01 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +		this.isSocial = true;
이 사용자가 일반 가입을했는지.
구글로 가입을 했는지
카카오로 가입을 했는지.

어떻게 알아요?

2024-10-13 05:29 UTC, hanbirang commented on src/main/java/site/coach_coach/coach_coach_server/auth/oauth/dto/CustomOAuth2User.java
> +	private final User user;
oAuth2 로그인으로 인증된 사용자 정보랑 애플리케이션 내 사용자 정보를 함께 관리하고 활용하기 위해서 넣었습니당.. 로그인 시마다 사용자 정보를 동기화하거나 업데이트할 수 있도록 넣었는데, 현재 oauth2 로그인 후 닉네임 입력을 따로 받도록 변경 예정이어서 필요없으면 수정할 계획입니다!

2024-10-13 05:32 UTC, hanbirang commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +	private String username;
이 username은 provider와 providerId 형태로 생성되고 DB에 저장됩니다 따라서 각 계정의 고유 식별자로 활용하기 위해 넣었습니다

2024-10-13 05:33 UTC, hanbirang commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +		this.isSocial = true;
일반 사용자인지 소셜 로그인인지는 isSocial로 알 수 있고 구글인지 카카오인지는 username을 통해 알 수 있습니당

2024-10-13 05:35 UTC, hanbirang commented
> 동일한 이메일로 가입하려고 하면 어떻게 되나요?

일반 회원가입 이메일과 소셜 로그인에서 동일한 이메일이면 중복 예외를 발생시킵니다 즉, 동일한 이메일로 구글, 카카오, 일반 회원가입을 시도하면 중복 가입 불가 처리가 됩니다 
계정 연동 기능도 생각을.. 해보았으나 일단 oauth2 구현을 목표로 두고, 다른 기능 개발 후 리팩토링하려고 했습니다!

2024-10-13 05:36 UTC, hanbirang commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +	private Boolean isSocial;
네 둘 다 연동은 안됩니당..

2024-10-13 05:49 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +	private String username;
그렇다먄 데이터 파싱이
필요하다는건데 따로 저장하는건 고려하지
않은
이유가 무엇인가요?

2024-10-13 06:47 UTC, hanbirang commented on src/main/java/site/coach_coach/coach_coach_server/user/domain/User.java
> +	private String username;
음.. 초기에는 정보가 딱히 필요하지 않을 것 같다고 판단했습니다 사용자 인증에 집중을 했고, 로그인한 사용자를 관리하는 데 있어서 소셜 제공자 정보가 큰 역할을 하지 않을 거라고 생각했습니다 그래서 간단하게 username에 정보를 포함하는 방식으로 구현했습니다 ..

2024-10-15 07:56 UTC, merged