refactor : 카테고리 테이블 삭제 및 관련 코드 리팩토링
Programmers-Coach-Coach/Coach-Coach-server pull request #328
Opened 2024-10-30 10:41 UTC by ckwogus37

# Pull requests
### 작업한 내용
- 기획 변경에 따른 categories 테이블 및 관련 코드 삭제
  - Routine - Action 구조로 루틴 데이터 구조 변경
    - 루틴과 운동 데이터가 한번에 같이 전송되는 방식으로 전환됨에 따라 루틴&운동 데이터 관리 방식 리팩토링
      -> 기존과 달리, 루틴과 운동 정보를 한번에 수정하여 데이터를 전송하게 되었습니다.(Figma 참고) 
      현재 데이터 전송 방식에 따라서 수정 기능을 구현하기 위해, 루틴 생성 시 의무적으로 4개의 운동을 보유하도록 리팩토링 하였습니다.
  - 기존 Category 역할을 Routine이 대신하도록 리팩토링 (is_completed, is_deleted 컬럼 추가)
  - Action 컬럼 및 참조 변경
  - 변경된 구조에 맞게 [루틴 추가/수정/조회, 루틴 완료/완료 취소] 기능 리팩토링
  - CompletedCategory -> CompletedRoutine 이름 및 참조 변경

- 루틴 반복일자 테이블(repeat_dates) 및 엔티티(RepeatDate) 추가
  - SQL 파일 및 코드 Merge 후에 실제 기능 개발 진행 예정 
 
### PR Point
- DB 테이블 구조 변경에 따른, 각자 맡은 파트와 관련된 테이블 및 로직에서 문제가 되는 점 있다면 확인 부탁드립니다!
- SQL 파일 적용 전에 로컬 DB에서 routines, routine_categories, actions, completed_categories 테이블 모두 비우고 진행하셔야 합니다! 

### 논의 사항 (선택)
- 10/31 목요일 백엔드 미팅 때, SQL 파일 내용 다같이 확인 및 Merge 먼저 진행해서 각자 맡은 파트 개발 진행하면 좋을 것 같습니다!

closed #324

2024-10-30 12:26 UTC, ksy90101 requested changes
데이터 구조가 많이 이상합니다.
허들로 가능할때 이야기 한번 하시죠.
DM으로 이야기 했듯이.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
>  	private String actionName;
지금보니 Action인데 ActionName으로 이름을 지은게 이상하네요.

이름은 원래는 테이블명의 컬럼, 객체지향관점에서의 객체의 상태를 나타내기 때문에 name이 더어울리는 이름이였을거 같네요.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
이 코드는 무엇인가요?
왜 JPA를 안쓰나요?

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +		List<Action> actions = actionRepository.findByRoutine_RoutineId(routineId);
지금 생각해보면, 일단 1. 해당 routinId가 존재하는지 체크할 필요는 없을까요?
즉, 그렇다면 routin조회는 불가피 할거 같고, JPA에서 이렇게 id로 찾을필요가 없어보이기도 하구요.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +		indexOfAction = 0;
이 코드의 의미는 무엇인가요?

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/common/domain/RepeatDateEnum.java
> +public enum RepeatDateEnum {
Java 내부가 가지고 있는

https://docs.oracle.com/javase/8/docs/api/?java/time/DayOfWeek.html

DatOfWeek라는 enum을 재활용하는게 더 좋을거 같고, 그게 차후에 관리하기도 용이할것이라고 기대합니다.

왜냐하면 기본적으로 요일이나 이런걸 모두 java의 코드로 할텐데, 그때마다 이 enum을 java에 맞춰서 파싱해야하고, 힘든 일이 될거 같은데요.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/controller/CompletedRoutineController.java
> +	@PostMapping("/v2/routines/{routineId}/completed")
혹시 v1을 남길것도 아니면서 v2로 하신 이유가 있나요?
버저닝에 대한 현재 생각하는바가 무엇인가요?

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/dto/CompletedRoutineDto.java
> +			.filter(action -> action.getActionName() != null)
이 조건이 있는데, 이게 과연 비지니스 로직이 아니라고 할수 있나요?
즉, from은 단순 파싱하는 역할을 하는데 여기서 이미 filter와 같은 특정한 로직을 해버린다면 이걸 모르는 사람들이 대부분일거 같아요.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/repository/CompletedRoutineRepository.java
> +		+ "LEFT JOIN FETCH r.coach "
LEFT JOIN이 필요했던건가요?

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/service/CompletedRoutineService.java
> +		if (!routine.getUser().getUserId().equals(userIdByJwt)) {
디미터의 법칙 위반.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/service/CompletedRoutineService.java
> +		completedRoutineRepository.findByUserRecord_RecordDateAndRoutine_RoutineId(
위에서 루틴을 찾았다면 routineId가 아니라 객체를 활용하여 하시는 방법도 해보시길.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineListDto.java
> +		return new RoutineListDto(Math.round(completionPercentage * 100) / 100.0f, this.routines);
100이 의미하는 바는 무엇인지? 100.0.f로는 또 나누는 이유가 무엇인지?

실제 로직이 잘 안읽혀 집니다.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
> +	void deleteRoutine(@Param("routineId") Long routineId);
https://velog.io/@max9106/JPA-soft-delete

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
> +	@Query("UPDATE Routine r SET r.isCompleted = FALSE WHERE r.routineId IS NOT NULL")
https://velog.io/@max9106/JPA-soft-delete
이게 전체 모든걸 바꾸는거 같은데 왜 필요한지?

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
> +	void deleteRoutine(@Param("routineId") Long routineId);
원래 삭제된걸 다시 돌리는 경우는 없을텐데요.

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
> +	void deleteRoutine(@Param("routineId") Long routineId);
소프트 딜리트에 대한 생각이 어떠신가요?

2024-10-30 12:26 UTC, ksy90101 commented on src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
> +	}
크론과 같은 작업은 따로 service로 관리해도 좋을수 있습니다.

2024-10-31 11:15 UTC, hanbirang approved these changes
코드 확인했습니다!!
복잡한 리팩토링의 세계... 🥹
수고하셨습니다!

2024-10-31 11:15 UTC, habbiness commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +	private static final Logger log = LoggerFactory.getLogger(ActionService.class);
이거 사용 중인가요????

2024-10-31 11:15 UTC, habbiness commented on src/main/java/site/coach_coach/coach_coach_server/routine/domain/Routine.java
> +	public void changIsCompleted() {
`changIsCompleted` 오타 확인했습니다!

2024-10-31 11:15 UTC, habbiness commented on src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
> +	@Column(name = "counts_or_minutes")
sets나 countsOrMinutes에 대한 Min, Max 값 설정은 필요없을까용???

2024-10-31 11:15 UTC, habbiness commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +	public void createAction(Routine newRoutine, List<ActionDto> actions) {
JPA를 사용했을 때 이런 방법도 있을 것 같긴 하네요! 회의 때 방법 아냐고 여쭤보셔서 찾아봤습니당..
```suggestion
	public void createAction(Routine newRoutine, List<ActionDto> actions) {
    List<Action> actionEntities = actions.stream()
        .map(actionDto -> Action.builder()
            .routine(newRoutine)
            .actionName(actionDto.actionName())
            .sets(actionDto.sets())
            .countsOrMinutes(actionDto.countsOrMinutes())
            .build())
        .collect(Collectors.toList());

    // 빈 액션을 채우는 부분
    int emptyActionCount = 4 - actions.size();
    for (int i = 0; i < emptyActionCount; i++) {
        actionEntities.add(Action.builder()
            .routine(newRoutine)
            .actionName(null)
            .sets(null)
            .countsOrMinutes(null)
            .build());
    }
    
    actionRepository.saveAll(actionEntities);
}
```

2024-10-31 13:30 UTC, jeeehdev approved these changes
코드 확인했습니다! 
기획상 변동이 많은 파트라 코드 수정이 복잡하셨을텐데 고생하셨습니다~!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
>  	private String actionName;
헛 그렇군요! 추후에 백엔드끼리 DB 및 엔티티 리팩토링때 고쳐보겠습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
Bulk Insert 기능을 사용하기위한 코드입니다!
JPA에서 save()와 saveAll() 메소드는 모두 단건 삽입으로 처리되는것으로 알고있어서
한번에 다수의 row를 삽입하기위해 사용하였습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +		List<Action> actions = actionRepository.findByRoutine_RoutineId(routineId);
updateAction 메서드가 실행되기 전에 updateRoutine 메서드 내부에서 해당 routineId에 대한 검증이 이뤄지고 있습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +		indexOfAction = 0;
기획 상, 하나의 루틴에 운동이 4개까지 생성할 수 있도록 제한되어 있습니다.
다만 루틴과 운동 데이터가 한번에 전송되는 상황에서 계속 변화되는 운동 데이터를 수정하기위해 
4개 이하로 운동 데이터가 수정되었을 경우, 나머지 운동들의 데이터를 초기화하도록 하였습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/common/domain/RepeatDateEnum.java
> +public enum RepeatDateEnum {
좋은 정보 감사드립니다!
문서 확인후에 enum 재활용을 적용해 보도록 하겠습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/dto/CompletedRoutineDto.java
> +			.filter(action -> action.getActionName() != null)
지금 보니 확실히 filter의 역할을 로직의 위치가 잘못되어있는것 같네요!
비즈니스 로직 (Service 계층)에서 처리할 수 있도록 리팩토링 해보겠습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/repository/CompletedRoutineRepository.java
> +		+ "LEFT JOIN FETCH r.coach "
서비스가 제공하는 "특정 일자의 완료 루틴 정보 제공" 부분에서
완료된 루틴에 대한 코치정보가 필요하여 Left Join을 통해 같이 가져온 것으로 알고있습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/completedroutine/service/CompletedRoutineService.java
> +		completedRoutineRepository.findByUserRecord_RecordDateAndRoutine_RoutineId(
말씀대로 기존에 조회한 객체를 활용해보도록 하겠습니다! 
감사합니다!!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/routine/dto/RoutineListDto.java
> +		return new RoutineListDto(Math.round(completionPercentage * 100) / 100.0f, this.routines);
전체 루틴 중에 완료한 루틴에 대한 비율 정보를 계산할 때, 소수점 2자리 수까지만 다루기 위해 사용하였습니다.
String.format으로 문자열 전환 후, 다시 float으로 만드는것보다 바로 float으로 사용하면 좋을것 같다고 생각했습니다.

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
> +	@Query("UPDATE Routine r SET r.isCompleted = FALSE WHERE r.routineId IS NOT NULL")
서비스 상, 매일 루틴을 완료/완료 취소할 수 있어야 합니다.
그래서 매일 정시에 모든 루틴의 is_completed를 false로 모두 초기화하기위해 Update 쿼리를 사용하였습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/routine/repository/RoutineRepository.java
> +	void deleteRoutine(@Param("routineId") Long routineId);
앗 soft delete 적용 후, 이전에 사용했던 쿼리를 삭제하지 않았네요..!
바로 삭제하도록 하겠습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/routine/service/RoutineService.java
> +	}
아하! 좋은 정보 감사합니다!!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/action/domain/Action.java
> +	@Column(name = "counts_or_minutes")
프론트파트 담당자가 정해놓은 설정 한번 확인해서 설정해보겠습니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +	public void createAction(Routine newRoutine, List<ActionDto> actions) {
saveAll을 사용한 방법이네요!
저도 찾아봤을 때, JPA 쿼리인 save와 saveAll의 경우엔 단건 삽입을 한다고해서 사용하지않았습니다 ㅠㅠ
한번에 다수의 row를 Insert하는 JPA 방법은 저도 좀 더 찾아보겠습니다! 감사합니다!

2024-11-02 08:43 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/routine/domain/Routine.java
> +	public void changIsCompleted() {
헛 감사합니다! 바로 수정하겠습니다!!

2024-11-02 09:14 UTC, ckwogus37 commented on src/main/java/site/coach_coach/coach_coach_server/action/service/ActionService.java
> +	private static final Logger log = LoggerFactory.getLogger(ActionService.class);
헛 확인후에 미사용중이면 삭제하도록 하겠습니다! 
감사합니다!!

2024-11-02 12:04 UTC, merged