Chore/2 add initial dockerfile
Programmers-Coach-Coach/Coach-Coach-server pull request #6
Opened 2024-07-27 07:21 UTC by jeeehdev

# Pull requests
### 작업한 내용
- ERD를 바탕으로 로컬에서 MySQL 데이터베이스를 설정하고 필요한 DDL 파일(테이블 생성 및 스키마 정의) 생성함
- `Dockerfile`을 작성하여 MySQL 이미지를 기반으로 사용자 정의 이미지를 생성함
- docker에 올려진 이미지를 쉽게 사용하기 위해 `docker-compose.yml` 파일을 작성함

**`docker-compose.yml`파일**
```
version: '3.8'

services:
  db:
    image: jeehh/coach-coach:mysql8.0.37
    restart: always
    container_name: coachcoach-db
    environment:
      MYSQL_USER: coachcoach
      MYSQL_PASSWORD: coach1234
      MYSQL_DATABASE: coachcoach
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  ..
``` 
### PR Point
- 백업 SQL 파일(`*.sql`)이 필요한 모든 테이블과 스키마를 정확하게 생성하는지 확인 부탁드립니다.
- 이미지를 빌드하고 푸시하는 과정에서 문제가 없는지, `docker build`와 `docker push` 명령어가 성공적으로 실행되는지 확인 부탁드립니다.
- 로컬에서 `docker-compose up -d` 명령어를 통해 컨테이너가 제대로 실행되는지 테스트해보셨나요? 로그를 확인하여 오류 메시지가 없는지 확인 부탁드립니다.

### 📸 스크린샷
| 사진 | 설명 |
|---|---|
|![image](https://github.com/user-attachments/assets/e9dc186e-5528-4023-8c21-9c495714ae3c)| `docker-compose up -d` 성공|

### 논의 사항 (선택)
- 환경 변수 설정을 .properties 파일에 저장하였습니다.

closed #2

2024-07-27 08:15 UTC, ckwogus37 approved these changes
도커파일 확인했습니다!

2024-07-27 08:31 UTC, hanbirang requested changes
수고하셨습니다!!! 코드 확인마쳤습니다
docker.. 저는 너무 어려운데 ,,, 멋있어요 지혜님,,🥹
sql에 대한 리뷰만 확인부탁드립니다!!

아!! 그리고 저희 PR 제목 컨벤션이 해당 브랜치에서 작업한 작업의 대표 커밋명이라서요! 그에 맞게 PR 제목 바꿔주시면 감사하겠습니다 🤩👍🏻👍🏻

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `minutes` int DEFAULT NULL,
앗! 저희 count랑 minutes를 합쳐서 `count_or_minutes` 필드로 수정한 것이 적용되지 않은 것 같습니다!!

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `is_open` tinyint DEFAULT NULL,
앗 이거 `is_open`의 DEFAULT는 true로 하는 거 어떨까요?? 저희 ERD에도 TRUE로 적혀있어서요!

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `routines_category_id` int NOT NULL,
사실... ERD 보고 이거 말씀드리려고 생각했었는데요,,, 음음 다른 테이블들 보니까 
```
테이블명 - 복수
참조키 - 단수 (해당 테이블 명의 단수형)
```
이렇더라고요 그러면 routine_categories를 참조하니, `routines_category_id`도 `routine_category_id`로 가는게 좋을 것 같다는 생각이 듭니다...!
ㅠ_ㅠ ERD에 조금 더 정확하게 적었어야 됐는데 헷갈리셨겠어요 죄송합니다 ㅠㅠ

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  CONSTRAINT `fk_completed_categories_routines_category_id` FOREIGN KEY (`routines_category_id`) REFERENCES `routine_categories` (`routine_category_id`),
만약 수정한다면 여기도 수정해야겠네요... ㅠㅠ

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `idinterested_sports_id` int NOT NULL AUTO_INCREMENT,
`idinterested_sports_id` 오타 확인했습니다!
아니면 앞에 일부러 id 붙이신 건가욤????

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `is_reading` tinyint NOT NULL,
여기 DEFAULT false 설정해주시면 좋을 것 같습니다!

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `user_coach_likes_id` int NOT NULL AUTO_INCREMENT,
```
테이블명 - 복수,
PK - 단수
```
다른 테이블들을 보니 이렇더라구요!
id이름을 따라서 `user_coach_like_id`로 하는 게 좋지 않을까싶습니다..
erd에서도 id이름이 이렇게 정해져있더라고요!

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `is_matching` tinyint NOT NULL,
이것도 default값을 false로 지정해주시면 좋겠습니다!

2024-07-27 08:31 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `password` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
저희 password에 해시된 password값이 들어가지 않나요
45로도 충분한가요?????? 생각해보니 충분할까,,궁금해서 여쭤봅니당...

2024-07-27 09:29 UTC, jeeehdev commented on mysql_coachcoach_ddl.sql
> +  `password` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
Erd에 적힌 값대로 작성했는데 해싱된 값 저장하려면 varchar(100)정도는 필요할 것 같네용.,! 아니면 혹시 모르니 255로 할까요?

2024-07-27 09:29 UTC, jeeehdev commented on mysql_coachcoach_ddl.sql
> +  `is_matching` tinyint NOT NULL,
넵!

2024-07-27 09:56 UTC, jeeehdev commented on mysql_coachcoach_ddl.sql
> +  `minutes` int DEFAULT NULL,
sql 관련 수정사항들 커밋했습니다!

2024-07-27 10:03 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +  `password` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
음음.. 그 사이인 150정도로 할까요?ㅋㅎㅋㅋㅋㅎㅋ

2024-07-27 10:10 UTC, hanbirang approved these changes
수정사항 다 확인했습니다! 감사합니다 수고하셨습니다!
password varchar값은.. 100도 충분할 것 같고... 음 지혜님이 원하는 값으로 지정하시죠 🤩👍🏻👍🏻

2024-07-27 10:10 UTC, hanbirang commented on mysql_coachcoach_ddl.sql
> +                                        KEY `fk_completed_categories_routines_category_id_idx` (`routine_category_id`),
여기 idx도 `fk_completed_categories_routines_category_id_idx`를 `fk_completed_categories_routine_category_id_idx`로 수정하면 좋을 것 같습니다!

2024-07-28 09:40 UTC, merged

2024-07-28 10:48 UTC, ksy90101 reviewed
모델은 entity 리뷰에서 하겠습니다.

아울러 이걸 계속 넣기 어려울수 있을거 같아요.
DROP TABLE IF EXISTS가 된다면 계속 ddl이 실행될때마다 계속 제거 되는거라고 생각이 드는데요.
그렇다면 실제 새로운 테이블이 추가되게 되었을때 어떻게 해야 할까요?

이럴땐 마이그레이션 도구를 많이 사용하는데요.

flywight와 같은 라이브러리를 한번 알아보세요.

2024-07-28 10:48 UTC, ksy90101 commented on Dockerfile
> +FROM mysql:8.0.37
dockerfile을 따로 만든 이유가 무엇인가요?

2024-07-29 07:23 UTC, jeeehdev commented on Dockerfile
> +FROM mysql:8.0.37
도커 이미지 생성하기 위해 만들었습니다! main에 올리지 않아도 되는 파일이라 다음 pr에서 삭제하도록 하겠습니다!

2024-07-29 07:24 UTC, ksy90101 commented on Dockerfile
> +FROM mysql:8.0.37
제가 말하고 싶은건, 기본적으로 제공하는 mysql 이미지를 쓰면 되는데 왜 따로 dockerfile을 만들어야 하는가? 었어요.

2024-07-29 08:12 UTC, jeeehdev commented on Dockerfile
> +FROM mysql:8.0.37
도커 세팅이 처음이라 기본적으로 제공하는 mysql 이미지 사용하는 방법을 고려하지 못했던 것 같습니다.. 제가 db data 셋팅을 포함한 이미지를 만들고 그 이미지를 빌드해서 사용하는 방식으로만 생각했던 것 같습니다.! 기본 이미지를 사용하는 방식으로 수정하도록 하겠습니다

2024-07-29 08:20 UTC, jeeehdev commented on Dockerfile
> +FROM mysql:8.0.37
flyweight으로 찾아보면 디자인 패턴이 나오는데, flyway같은 db 마이그레이션 도구 활용해보면 되는 걸까요..?! 혹시 추천해주신 다른 이유가 있으실까 하여 여쭤봅니다!

2024-07-29 13:18 UTC, ksy90101 commented on Dockerfile
> +FROM mysql:8.0.37
아... 죄송해요..
flyway말한거였어요;;